UCUG/urls.py
from django.contrib import admin
from django.urls import path, include
from UCUG import views

urlpatterns = [
    path('', views.home),
    path('home/', views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),

    path('create_announcement/', views.create_announcement, name='create_announcement'),
    path('edit_announcement/', views.edit_announcement, name="edit_announcement"),
    path('delete_announcement/<int:id>', views.delete_announcement, name="delete_announcement"),

    path('', include('ucug_auth.urls')),
    path('', include('ucug_forum.urls')),
]

UCUG/models.py
from UCUG.settings import DEBUG
from django.db import models

from ucug_auth.models import User


class Announcement(models.Model):
    title = models.CharField(max_length=64, null=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    created_UTC = models.DateTimeField(auto_now_add=True)

    def public_data(self):
        data = {
            "id" : self.id,
            "title": self.title,
            "content" : self.content,
            "author": self.author.id,
        }
        return data

class Session(models.Model):
    time_UTC = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField(null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    method = models.CharField(max_length=8)
    route = models.CharField(max_length=32)

    MESSAGES = (
        ('NONE', ''),
        ('NO_AUTH', 'NO_AUTH'),
        ('BAD_INPUT', 'BAD_INPUT'),
    )
    message = models.CharField(
        max_length=16,
        choices=MESSAGES,
        default="NONE",
    )

def record_session(request, message=None):
    # When hosting on pythonanywhere (DEBUG=False) this is where the client IP is stored.
    # Using the regular method would return the ip of a pythonanywhere server.
    if DEBUG == False:
        ip = request.headers['X-Real-IP']
    else:
        ip = request.META.get('REMOTE_ADDR')

    # If user is not logged in then request.user is a special type "AnonymousUser" which cannot be referenced
    # properly in the sessions table. Must be set to none.
    if isinstance(request.user, User):
        user = request.user
    else:
        user=None

    session = Session(ip=ip,
                      method=request.method,
                      route=request.path,
                      user=user,
                      message=message if message else "NONE")
    return session.save()

ucug_forum/models.py
from django.db import models
from django.db.models import Q
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from ucug_auth.models import User


# Django automatically creates an integer id primary key.
class Forum(models.Model):
    created_UTC = models.DateTimeField(auto_now_add=True)
    updated_UTC = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    title = models.CharField(max_length=64, default="Null")
    description = models.CharField(max_length=256, null=True, blank=True)

    def public_data(self):
        if self.owner:
            owner_id = self.owner.id
            owner_name = self.owner.username
            if self.owner.is_superuser:
                owner_class = "super"
            elif self.owner.is_staff:
                owner_class = "staff"
            else:
                owner_class = "user"
        else:
            owner_name = "Anon"
            owner_class = "User"
            owner_id = 0

        data = {
            "id" : self.id,
            "title" : self.title,
            "description" : self.description,
            "owner_id" : owner_id,
            "owner_name" : owner_name,
            "owner_class" : owner_class,
            "owner_url" : "/profile/" + owner_name,
        }
        return data

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=64, default="Null")
    content = models.TextField(max_length=1024, null=True, blank=True)

    created_UTC = models.DateTimeField(auto_now_add=True)
    updated_UTC = models.DateTimeField(auto_now=True)

    mentions = models.ForeignKey('self', related_name="post_mention", on_delete=models.SET_NULL, null=True, blank=True)
    parent_forum = models.ForeignKey(Forum, on_delete=models.CASCADE, null=True, blank=True)
    parent_post = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    reply_count = models.SmallIntegerField(null=False, default=0)
    like_count = models.SmallIntegerField(null=False, default=0)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    ip_owner = models.GenericIPAddressField(null=True, blank=True)

    def public_data(self, user=None):
        if self.owner:
            owner_name = self.owner.username
            owner_id = self.owner.id
            if self.owner.is_superuser:
                owner_class = "super"
            elif self.owner.is_staff:
                owner_class = "staff"
            else:
                owner_class = "user"
        else:
            owner_name = "Anon"
            owner_class = "user"
            owner_id = 0
        
        if user and Like.objects.filter(user=user.id, post=self.id).exists():
            liked_by_user = True
        else:
            liked_by_user = False

        data = {
            "id" : self.id,
            "title" : self.title,
            "content" : self.content,
            "created" : self.created_UTC.strftime("%H:%M %m/%d/%y"),
            "owner_id" : owner_id,
            "owner_name" : owner_name,
            "owner_class" : owner_class,
            "owner_url" : "/profile/" + owner_name,
            "parent_post" : self.parent_post.title if self.parent_post else None,
            "parent_forum" : self.parent_forum.title if self.parent_forum else None,
            "like_count" : self.like_count,
            "liked_by_user" : liked_by_user,
            "reply_count" : self.reply_count,
        }
        return data

    def __str__(self):
        return self.title

# A functional abstraction for requesting posts to display.
# Parameters correspond to different query selectors on the front end.
# params of None equates to "all"
# page_number is used for pagination & iteratively rendering content.

# How many posts to display at a time.
PAGE_LENGTH = 15

def get_posts(ordering="Most Recent", title=None, content=None, author=None, p_forum=None, p_post=None, page_number=0):
    query = Q()

    # Filter by post contents
    if title and content:
        query &= Q(title__contains=title)
        query |= Q(content__icontains=content)
    elif title:
        query &= Q(title__icontains=title)
    elif content:
        query &= Q(content__icontains=content)
    
    # Filter by author
    if author:
        query &= Q(owner__username__icontains=author)

    # Filter by location
    if p_forum:
        query &= Q(parent_forum__id=p_forum)
    elif p_post:
        query &= Q(parent_post__id=p_post)

    # Make the constructed query with the wanted ordering
    if ordering == "Most Recent":
        posts = Post.objects.filter(query).order_by("-created_UTC")
    elif ordering == "Oldest":
        posts = Post.objects.filter(query).order_by("created_UTC")
    elif ordering == "Most Liked":
        posts = Post.objects.filter(query).order_by("-like_count")
    else:
        posts = Post.objects.filter(query)

    return posts

class Like(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'], name='user_post_pair'
            )
        ]

    user = models.IntegerField()
    post = models.IntegerField()

    created_UTC = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} -> {self.post}"

UCUG/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

from datetime import datetime

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'form-control form-control-lg'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'form-control form-control-lg'
    }))

    class Meta:
        model = User
        fields = ('username', "password1", "password2")
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Username',
                'class': 'form-control form-control-lg'
            })
        }
    
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.joined = user.last_active = datetime.now()
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        print(user)
        return user

UCUG/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
import json

from UCUG.models import record_session
from UCUG.models import Announcement, User
from ucug_forum.models import Forum

def home(request):
    record_session(request)
    announcements = Announcement.objects.all()
    forums = Forum.objects.all()

    announcements_json = serializers.serialize("json", announcements)

    return render(request=request, template_name="home.html",
                context = {"announcements": announcements,
                            "forums": forums,
                            "announcement_data": announcements_json})

def create_announcement(request):
    # Check if the user can make announcements
    if not request.user.has_perm("add_announcement"):
        record_session(request, "NO_AUTH")
        return HttpResponse("Nice try!")

    announcement = Announcement(title=request.POST["title"],
                                content=request.POST["content"],
                                author=request.user)
    announcement.save()

    # Return new announcement data to be rendered.
    announcement_data = announcement.public_data()
    author_data = announcement.author.public_data()

    return HttpResponse(json.dumps([announcement_data, author_data]))

def edit_announcement(request):
    record_session(request)

    # Check if the user can edit announcements
    if not request.user.has_perm("edit_announcement"):
        record_session(request, "NO_AUTH")
        return HttpResponse("Nice try!")

    announcement = Announcement.objects.get(id=request.POST["id"])
    announcement.title = request.POST["title"]
    announcement.content = request.POST["content"]
    announcement.save()

    return HttpResponse("Announcement {}: \"{}\" edited.".format(announcement.id, announcement.title))

def delete_announcement(request, id):
    if not request.user.has_perm("delete_announcement"):
        record_session(request, "NO_AUTH")
        return HttpResponse("Nice try!")

    announcement = Announcement.objects.get(id=id)
    title = announcement.title
    announcement.delete()
    return HttpResponse("Sucessfully deleted announcement {}: \"{}\"".format(id, title))

UCUG/templates/announcement.html
<v-row id="announcement{{announcement.id}}">
    <v-card outlined
            width="100%"
            elevation=6
            class="ma-2 rounded-lg"
            style="border-left: 8px solid rgb(39,86,139)">
        <v-card-title>
            {{ announcement.title }}
            <v-spacer></v-spacer>
            <!-- Author Tag -->
            {% if announcement.author %}
                {% if announcement.author.is_superuser %}
                <v-chip href="/profile/{{ announcement.author.username }}" color="orange" text-color="white">
                    <v-icon left>mdi-shield-star</v-icon>{{ announcement.author.username }}
                </v-chip>
                {% elif announcement.author.is_staff %}
                <v-chip href="/profile/{{ announcement.author.username }}" color="success" text-color="white">
                    <v-icon left>mdi-shield-account</v-icon>{{ announcement.author.username }}
                </v-chip>
                {% else %}
                <v-chip href="/profile/{{ announcement.author.username }}" color="info" text-color="white">
                    <v-icon left>mdi-account</v-icon>{{ announcement.author.username }}
                </v-chip>
                {% endif %}
            {% endif %}
        </v-card-title>

        <v-card-text>
            {{ announcement.content }}
        </v-card-text>

        {% if perms.UCUG.change_announcement %}
        <v-card-actions>
            <v-btn small class="mx-1" fab color="info"><v-icon>mdi-pencil</v-icon></v-btn>
            <v-btn v-on:click="delete_announcement({{ announcement.id }})" small class="mx-1" fab color="error"><v-icon>mdi-delete</v-icon></v-btn>
        </v-card-actions>
        {% endif %}
    </v-card>
</v-row>

UCUG/templates/footer.html
        <v-footer app
            absolute
            padless
            dark>
            <v-card tile width="100%" color="rgb(39,86,139)" text-align="center" class="lighten-1 text-center">
                <v-card-text>
                    <v-btn href="/home" text>
                        <img src="/static/icons/home_white.png">
                        Home
                    </v-btn>

                    {% if user.is_authenticated %}
                    <v-btn href="#" text>
                        <img src="/static/icons/profile_white.png">
                        {{ user.username }}
                    </v-btn>
                    <v-btn href="/logout" text>
                        <img src="/static/icons/log_white.png">
                        Log Out
                    </v-btn>
                    {% else %}
                    <v-btn href="/login" text>
                        <img src="/static/icons/log_white.png">
                        Log In
                    </v-btn>
                    <v-btn href="/register" text>
                        <img src="/static/icons/register_white.png">
                        Register
                    </v-btn>
                    {% endif %}
                </v-card-text>

                <v-col
                class="lighten-2 py-4 text-center white--text"
                cols="12">
                    <strong>[[ new Date().getFullYear() ]] — DNGV</strong>
                </v-col>
            </v-card>
        </v-footer>

UCUG/templates/header.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Custom UCUG Styling -->
        <link rel="stylesheet" href="/static/css/header.css">

        <!-- Vue JS -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.min.js"></script>

        <!-- Vuetify -->
        <script src="https://cdn.jsdelivr.net/npm/vuetify@2.6.12/dist/vuetify.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/@mdi/font@6.x/css/materialdesignicons.min.css" rel="stylesheet">

        <!-- Axios JS -->
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

        <title>UCUG</title>
    </head>
    <body>
        <!-- The v-content tag separates the sites content from its other components,
             such as the navbar. Without this tag, the content would be hidden under
             the nav bar. -->

        <v-app id="app">
            {% include "navbar.html" %}

            <v-main>
                <!-- The v-container tag helps center contents to the page -->
                <v-container fluid>
                    <v-row>
                        <v-col cols="1" xs="1" sm="3" md="2" lg="3"></v-col>
                        <v-col xs="10" sm="9" md="7" lg="5">
                            {% block content %}{% endblock %}
                        </v-col>
                        <v-col cols="1" xs="1" sm="0" md="3" lg="4"></v-col>
                    </v-row>
                </v-container>
            </v-main>

            {% include "footer.html" %}
        </v-app>

        <script type="text/javascript">
            vue = new Vue({
                el: '#app',
                vuetify: new Vuetify(),
                delimiters: ['[[', ']]'],
                icons: {
                    iconfont: 'mdiSvg'
                },
                data: () => ({
                    // Navigation drawer which can be toggled for small screens
                    drawer: false,
                    // Group ???
                    group: null,

                    title_rules: [
                        title => !!title || "You must have a title!",
                        title => (title || '').length <= 64 || "The title can't be longer than 64 characters!",
                    ],
                    content_rules: [
                        content => (content || '').length <= 256 || "The content can't be longer than 256 characters!",
                    ],
                    
                    announcement_create_form: false,
                    announcement_edit_form: false,
                    edit_announcement_valid: false,
                    edit_announcement_id: 0,
                    edit_announcement_title: "",
                    edit_announcement_content: "",
                    create_announcement_valid: false,
                    create_announcement_title: "",
                    create_announcement_content: "",

                    announcements: { {% for announcement in announcements %}
                                        {{ announcement.id }} :
                                        {
                                            "id" : "{{ announcement.id }}",
                                            "title" : "{{ announcement.title|escapejs }}",

                                            "author_name" : "{{ announcement.author.username|escapejs }}",
                                            "author_id" : "{{ announcement.author.id }}",
                                            "author_class" : {% if announcement.author.is_superuser %}
                                                                "super"
                                                            {% elif announcement.author.is_staff %}
                                                                "staff"
                                                            {% else %}
                                                                "user"
                                                            {% endif %},
                                            "author_url" : "/profile/{{ announcement.author.username|escapejs }}",

                                            "content" : "{{ announcement.content|escapejs }}",
                                            "can_edit" : {% if perms.UCUG.change_announcement %}
                                                            true
                                                        {% else %}
                                                            false
                                                        {% endif %}
                                        },
                                    {% endfor %}},
                    forums : { {% for forum in forums %}
                                {{ forum.id }} : {
                                    "id" : {{ forum.id }},
                                    "title" : "{{ forum.title }}",
                                    "description" : "{{ forum.description|escapejs }}",
                                    "url" : "/forum/" + "{{ forum.title }}",

                                    {% if forum.owner %}
                                    "owner_name" : "{{ forum.owner.username }}",
                                    "owner_url" : "/profile/{{ forum.owner.username }}",
                                    "owner_class" : {% if forum.owner.is_superuser %}
                                                    "super"
                                                    {% elif forum.owner.is_staff %}
                                                    "staff"
                                                    {% else %}
                                                    "user"
                                                    {% endif %},
                                    {% endif %}

                                    "can_edit" : {% if perms.UCUG.change_forum %}
                                                    true
                                                {% else %}
                                                    false
                                                {% endif %},
                                },          
                            {% endfor %}},

                    forum_create_form: false,
                    create_forum_valid: false,
                    create_forum_title: "",
                    create_forum_description: "",
                }),
                methods: {
                    toggle_announcement_create_form() {
                        this.announcement_create_form = !this.announcement_create_form
                    },
                    toggle_announcement_edit_form(id) {
                        this.announcement_edit_form = !this.announcement_edit_form
                        if (this.announcement_edit_form) {
                            this.edit_announcement_id = id
                            this.edit_announcement_title = this.announcements[id].title
                            this.edit_announcement_content = this.announcements[id].content
                        }
                    },
                    edit_announcement() {
                        if (!this.edit_announcement_valid) return false
                        
                        announcement = this.announcements[this.edit_announcement_id]

                        let data = new FormData()
                        data.append("id", this.edit_announcement_id)
                        data.append("title", this.edit_announcement_title)
                        data.append("content", this.edit_announcement_content)
                        data.append("csrfmiddlewaretoken", '{{ csrf_token }}')

                        axios.post("{% url 'edit_announcement' %}", data)
                            .then(res => {this.announcement_edit_form = false;
                                        announcement.title = this.edit_announcement_title
                                        announcement.content = this.edit_announcement_content
                                        console.log("Successfully edited announcement.")})
                            .catch(err => console.log(err))
                    },
                    create_announcement() {
                        if (!this.create_announcement_valid) {return false}

                        let data = new FormData()
                        data.append("title", this.create_announcement_title)
                        data.append("content", this.create_announcement_content)
                        data.append("csrfmiddlewaretoken", '{{ csrf_token }}')

                        axios.post("{% url 'create_announcement' %}", data)
                            .then(res => {this.announcement_create_form = false;
                                        this.create_announcement_title = "";
                                        this.create_announcement_content = "";
                                        this.render_announcement(res);
                                        console.log("Successfully created announcement.")})
                            .catch(err => console.log(err))
                    },
                    render_announcement(response_data) {
                        // Add the announcement to the component's announcement list to render it dynamically.
                        announcement = response_data.data[0]
                        author = response_data.data[1]

                        if (author.is_superuser) {
                            author_class = "super"
                        } else if (author.is_staff) {
                            author_class = "staff"
                        } else {
                            author_class = "user"
                        }
                        
                        this.announcements[announcement.id] = {
                            "id" : announcement.id,
                            "title" : announcement.title,
                            "content" : announcement.content,

                            "author_id" : author.id,
                            "author_name" : author.username,
                            "author_class" : author_class,
                            "author_url" : author.url,
                            "can_edit" : true,
                        }
                    },
                    delete_announcement(id) {
                        // Remove it from the database
                        axios.delete("/delete_announcement/" + id, {
                                headers: {
                                    "X-CSRFTOKEN": "{{ csrf_token }}"
                                }
                            })
                            .then(res => console.log(res.data))
                            .catch(err => console.log(err))

                        // Remove it from the webpage
                        Vue.delete(vue.announcements, id)

                        // Close the applicable edit form.
                        if (this.edit_announcement_id == id) {
                            this.edit_announcement_id = null
                            this.announcement_edit_form = false
                        }
                    },

                    toggle_forum_create_form() {
                        this.forum_create_form = !this.forum_create_form
                    },
                    create_forum() {
                        if (!this.create_forum_valid) {return false}

                        let data = new FormData()
                        data.append("title", this.create_forum_title)
                        data.append("description", this.create_forum_description)
                        data.append("csrfmiddlewaretoken", '{{ csrf_token }}')

                        axios.post("{% url 'create_forum' %}", data)
                            .then(res => {this.forum_create_form = false;
                                        this.create_forum_title = "";
                                        this.create_forum_description = "";
                                        this.render_forum(res);
                                        console.log("Forum successfully created.")})
                            .catch(err => console.log(err))
                    },
                    render_forum(response_data) {
                        // Add the forum to the component's list of forums to be rendered dynamically.
                        forum = response_data.data[0]
                        owner = response_data.data[1]
                        
                        if (owner.is_superuser) {
                            owner_class = "super"
                        } else if (owner.is_staff) {
                            owner_class = "staff"
                        } else {
                            owner_class = "user"
                        }

                        this.forums[forum.id] = {
                            "id" : forum.id,
                            "title" : forum.title,
                            "description" : forum.description,
                            "url" : "/forum/" + forum.title,

                            "owner_name" : owner.username,
                            "owner_class" : owner_class,
                            "owner_url" : owner.url,

                            "can_edit" : true,
                        }
                    },
                },
                watch: {
                    group () {
                        this.drawer = false
                    }
                }
            })
        </script>
    </body>
</html>

UCUG/templates/invalid_profile.html
{% extends "auth_header.html" %}

{% block content %}
INVALID
{% endblock %}

UCUG/templates/navbar.html
<v-app-bar app elevation="15" fixed dark color="rgb(39,86,139)">
    <v-spacer class="d-none d-sm-flex"></v-spacer>

    <v-app-bar-nav-icon @click.stop="drawer = !drawer" class="d-flex d-sm-none"></v-app-bar-nav-icon>

    <v-toolbar-title>UCUG</v-toolbar-title>

    <v-spacer class="d-none d-sm-flex"></v-spacer>
    <v-toolbar-items class="d-none d-sm-flex">
        <v-btn href="/home" text>
            <img src="/static/icons/home_white.png">
            Home
        </v-btn>
        {% if user.is_authenticated %}
        <v-btn href="/profile/{{ user.username }}" text>
            <img src="/static/icons/profile_white.png">
            {{ user.username }}
        </v-btn>
        <v-btn href="/logout" text>
            <img src="/static/icons/log_white.png">
            Sign Out
        </v-btn>
        {% else %}
        <v-btn href="/login" text>
            <img src="/static/icons/log_white.png">
            Log In
        </v-btn>
        <v-btn href="/register" text>
            <img src="/static/icons/register_white.png">
            Register
        </v-btn>
        {% endif %}
    </v-toolbar-items>
    <v-spacer></v-spacer>
</v-app-bar>

<v-navigation-drawer app v-model="drawer" color="rgb(39,86,139)" dark temporary>
    <v-list nav dense>
        <v-list-item-group v-model="group">
            <v-list-item href="/home" text>
                <img src="/static/icons/home_white.png">
                Home
            </v-list-item>
            {% if user.is_authenticated %}
            <v-list-item href="/profile/{{ user.username }}" text>
                <img src="/static/icons/profile_white.png">
                {{ user.username }}
            </v-list-item>
            <v-list-item href="/logout" text>
                <img src="/static/icons/log_white.png">
                Sign Out
            </v-list-item>
            {% else %}
            <v-list-item href="/login" text>
                <img src="/static/icons/log_white.png">
                Log In
            </v-list-item>
            <v-list-item href="/register" text>
                <img src="/static/icons/register_white.png">
                Register
            </v-list-item>
            {% endif %}
        </v-list-item-group>
    </v-list>
</v-navigation-drawer>